name: Building kernel

on: # [push]
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      COMPILER:
        description: 'compilers used'
        required: true
        default: 'NeutronClang'
  watch:
    types: [started]

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  REPO: TelegramAt25/android_kernel_xiaomi_selene
  RUN_NUM: ${{ github.run_number }}_${{ github.run_attempt }}
  KERNEL_BRANCH: thirteen
  COMPILERS: ${{ github.event.inputs.COMPILER }}
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: actions/checkout@master
        - name: copy stuff to the docker dir lmao
          run: |
            cp *.sh ./docker/
            cp -r toolchains ./docker/
        - name: notify the start of the workflow
          run: |
            bash tg_utils.sh msg "gh $RUN_NUM: workflow started"
        - name: drop all work to docker and flee
          uses: ./docker/
          id: a

