name: Building kernel

on: # [push]
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  REPO: ${{ secrets.REPO }}
  KERNEL_BRANCH: ${{ secrets.KERNEL_BRANCH }}
  SCRIPT: ${{ secrets.SCRIPT }}
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: actions/checkout@master

        - name: initialize environment
          run: |
            curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d "disable_web_page_preview=true" \
            -d "parse_mode=html" \
            -d text="initializing environment for kernel compilation"
            sudo apt-get update
            sudo apt-get install llvm lld bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev openssl python zip zstd make clang gcc-arm-linux-gnueabi software-properties-common -y
        - name: clone kernel source
          run: |
            curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d "disable_web_page_preview=true" \
            -d "parse_mode=html" \
            -d text="cloning kernel source"
            git clone --depth=1 https://github.com/$REPO -b $KERNEL_BRANCH begonia
        - name: run compilation script
          run: |
            curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d "disable_web_page_preview=true" \
            -d "parse_mode=html" \
            -d text="running compilation script"
            cd begonia
            sudo bash ../$SCRIPT
        - name: upload
          run: |
            cd begonia
            ZIP=$(echo *.zip)
            if [ -e $ZIP ]; then
                curl -F chat_id="$CHAT_ID" \
                -F document=@"$ZIP" \
                -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument \
                -F caption="Test it @TeraaBytee"
            else
                curl -F chat_id="$CHAT_ID" \
                -F document=@"out/error.log" \
                -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument \
                -F caption="Check it @TeraaBytee"
            fi

