name: Building kernel

on: # [push]
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  KERNEL_URL: ${{ secrets.KERNEL_URL }}
  KERNEL_BRANCH: ${{ secrets.KERNEL_BRANCH }}
  KERNEL_PATH: ${{ secrets.KERNEL_PATH }}
  SCRIPT: ${{ secrets.SCRIPT }}
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Initializing environment
          run: |
            curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d "disable_web_page_preview=true" \
            -d "parse_mode=html" \
            -d text="Initializing environment for compiling kernel"
            sudo apt-get update
            sudo apt-get install bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev openssl python zip zstd make clang gcc-arm-linux-gnueabi software-properties-common -y
        - name: Clone source kernel
          run: |
            curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d "disable_web_page_preview=true" \
            -d "parse_mode=html" \
            -d text="Clone source kernel"
            git clone --depth=1 $KERNEL_URL -b $KERNEL_BRANCH $KERNEL_PATH
        - name: Run scripts
          run: |
            curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d "disable_web_page_preview=true" \
            -d "parse_mode=html" \
            -d text="Run scripts"
            cd $KERNEL_PATH
            sudo bash ../$SCRIPT
        - name: Upload
          run: |
            cd $KERNEL_PATH
            ZIP=$(echo *.zip)
            curl -F chat_id="$CHAT_ID" \
            -F document=@"$ZIP" \
            -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument \
            -F caption="Test it @TeraaBytee"
